name: Build Cinny
on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build-cinny:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Cinny
        run: git clone https://github.com/cinnyapp/cinny.git .
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'
      - name: Install dependencies
        run: npm i
      - name: Build project
        run: pnpm build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: dist
          name: cinny-build
      - name: Prepare for pushing to cinny-builds
        uses: actions/checkout@v4
        with:
          path: cinny-builds
      - name: Push to cinny-builds
        run: |
          git config --global user.name "Logout"
          git config --global user.email "logout@users.noreply.github.com"
          sudo apt install zip -y
          cd dist
          zip -r ../cinny.zip *
          cd ..
          mv dist /tmp/cinny
          mv cinny.zip /tmp/cinny.zip
          rm -rf .git
          cd cinny-builds
          mv .git /tmp/cinny.git
          rm -rf ./*
          mv /tmp/cinny.git .git
          mv /tmp/cinny dist
          mv /tmp/cinny.zip cinny.zip
          # git remote set-url origin https://git@github.com/Exponential-Workload/cinny-desktop.git
          git add .
          git commit -m "build: Build Cinny"
          git push origin cinny-builds
