name: Build Cinny
on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build-cinny:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Cinny
        run: git clone https://github.com/cinnyapp/cinny.git .
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'
      - name: Install dependencies
        run: npm i
      - name: Build project
        run: pnpm build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: dist
          name: cinny-build
      - name: Prepare for pushing to cinny-builds
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v4
        with:
          path: cinny-builds
          ref: cinny-builds
      - name: Push to cinny-builds
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          git config --global user.name "Logout"
          git config --global user.email "logout@users.noreply.github.com"
          mv dist /tmp/cinny
          rm -rf .git
          cd cinny-builds
          mv .git /tmp/cinny.git
          rm -rf ./*
          mv /tmp/cinny.git .git
          mv /tmp/cinny/* ./
          # git remote set-url origin https://git@github.com/Exponential-Workload/cinny-desktop.git
          git add .
          git commit -a -m "build: Build Cinny ($(date -u +%Y-%m-%dT%H:%M:%S%Z))"
          git push -u origin cinny-builds
