name: Build Cinny
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-cinny:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Cinny
        run: git clone https://github.com/cinnyapp/cinny.git .
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Install jq
        run: sudo apt install jq
      - name: Update Version
        run: jq '.version = "'"$(jq .version package.json -r)-git-$(git rev-parse --short HEAD | tr -d '[:space:]')"'"' package.json > tmp.json && mv tmp.json package.json
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'
      - name: Install dependencies
        run: |
          npm i || pnpm i
          pnpm i -g vite
      - name: Upgrade dependencies
        run: npm upgrade
      - name: Build project
        run: pnpm build
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: dist
          name: cinny-build
