name: Deploy Master Branch
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'deploy-master'
  cancel-in-progress: true

jobs:
  build-os:
    uses: ./.github/workflows/build.yml
  deploy:
    runs-on: ubuntu-latest
    needs: [build-os]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Cinny
        uses: actions/download-artifact@v4
        with:
          name: cinny-build
          path: ./_build/cinny
      - name: Download Ubunut
        uses: actions/download-artifact@v4
        with:
          name: build-ubunut
          path: ./_build/ubunut
      - name: Download Michaelsoft Binbows
        uses: actions/download-artifact@v4
        with:
          name: build-binbows
          path: ./_build/window
      # - name: Download Sacking the OS
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: build-sackos
      #     path: ./_build/mack
      - name: Remove .github
        run: rm -rf .github
      - name: Create Indexes
        uses: Exponential-Workload/create-index-action@master
        with:
          dir: '.'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
