name: Deploy Release Binaries

on:
  workflow_dispatch:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  version-install-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install jq
        run: sudo apt install jq -y;
      - name: Set version in Installation Script
        run: |
          sed 's/releases\/latest\/download/releases\/download\/v'$(jq .version package.json)/ util/install-from-dist.sh > util/install-from-dist-v.sh
          mv util/install-from-dist-v.sh util/install-from-dist.sh
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: util
          name: util-dir
  build-os:
    uses: ./.github/workflows/build.yml
  release:
    runs-on: ubuntu-latest
    needs: [build-os, version-install-script]
    steps:
      - name: Install zip
        run: sudo apt install zip -y;
      - name: Download Util
        uses: actions/download-artifact@v4
        with:
          name: util-dir
          path: ./util
      - name: Download Ubunut
        uses: actions/download-artifact@v4
        with:
          name: build-ubunut
          path: ./bin/linux
      - name: Download Michaelsoft Binbows
        uses: actions/download-artifact@v4
        with:
          name: build-binbows
          path: ./bin/windows
      - name: Download Plain Cinny
        uses: actions/download-artifact@v4
        with:
          name: cinny-build
          path: ./bin/cinny-static
      - name: Make output dir
        run: mkdir out
      - name: Chmod Binaries
        run: chmod +x --recursive bin
      - name: Linux Install Script
        run: mv util/install-from-dist.sh out/linux-install-x64.sh;
      - name: Tar Linux Plain
        run: cd bin/linux/Cinny\ Desktop-linux-x64; tar -czvf ../../../out/linux-bin-x64.tar.gz .;
      - name: Zip Linux Plain
        run: mv bin/linux/make/zip/linux/x64/Cinny\ Desktop-linux-x64-*.zip ./out/linux-bin-x64.zip;
      - name: Deb
        run: mv bin/linux/make/deb/x64/cinny-desktop_*_amd64.deb ./out/debian-x64.deb;
      - name: Zip Windows Plain
        run: cd bin/windows/Cinny\ Desktop-win32-x64; zip -r ../../../out/windows-bin-x64.zip .;
      - name: Squirrel exe
        run: mv bin/windows/make/squirrel.windows/x64/Cinny\ Desktop-*\ Setup.exe ./out/windows-setup-x64.exe;
      - name: Tar Static Cinny
        run: cd bin/cinny-static && tar -czvf ../../out/cinny-static.tar.gz .
      - name: Chmod Output
        run: chmod +x --recursive out
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            out/linux-install-x64.sh
            out/linux-bin-x64.tar.gz
            out/linux-bin-x64.zip
            out/debian-x64.deb
            out/windows-bin-x64.zip
            out/windows-setup-x64.exe
            out/cinny-static.tar.gz
